#!/usr/bin/env bash

# Set up autograder files
cp -a submission/. source/

cd source

# Can also wget here with a server location for an autograder .R script 
# This is very useful to avoid rebuilding the autograder on Gradescope every time you update the .R script.

Rscript autograde.R